addr: "localhost:8080"
timeout_read: "15s"
timeout_write: "15s"
db_path: "postgres://user:secret@localhost:5432/loyalty?sslmode=disable"
logger_level: "info"
logger_format: "json"
mq_path: "amqp://admin:password@localhost:5672/"